name: CD Pipeline
# Only trigger, when the build workflow succeeded i.e. Push Docker Image
on:
  workflow_run:
    workflows: ["Push Docker Image"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER_NAME}}
        run: sudo docker pull $DOCKER_USER/diabetes-fastapi:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f diabetes-fastapi-container || true

      - name: Run Docker Container
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER_NAME}}
        run: sudo docker run -it -d -p 8001:8001 --name diabetes-fastapi-container $DOCKER_USER/diabetes-fastapi:latest
